In [2]:
import numpy as np

np.random.randint(10)

8

In [3]:
dnp = np.array([1, 2, 3, 5, 6])

In [4]:
dnp


array([1, 2, 3, 5, 6])

In [5]:
list2 = [11, 22, 33]

In [6]:
dnp = np.array(list2)

In [7]:
dnp = np.insert(dnp, 2, 10)

In [8]:
dnp

array([11, 22, 10, 33])

In [9]:
np.where(dnp ==22)

(array([1], dtype=int64),)

In [23]:
mda = np.array([[1,2,3], [4,5,6], [7,8,9]])
mda

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
mda = mda+50
mda

array([[51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [25]:
mda

array([[51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [27]:
mda[1, 0:4]=150
mda

array([[ 51,  52,  53],
       [150, 150, 150],
       [ 57,  58,  59]])

In [28]:
np.std(mda)

44.85532298401161

In [29]:
np.mean(mda)

86.66666666666667